version: 2
jobs:
  build-amd64:
    docker:
      - image: docker:18.09.9-git
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: docker build -t amd64 -f amd64.dockerfile .
          no_output_timeout: 3600 
      - run: docker run --name temp-container amd64 /bin/true
      - run: docker cp temp-container:/@sixriver/ .
      - run: docker cp temp-container:/target_path.txt .
      - run: docker cp temp-container:/binary_path.txt .
      - run: docker rm temp-container
      - run: ls -la
      - persist_to_workspace:
          root: ./
          paths:
            - target_path.txt
            - binary_path.txt
            - '@sixriver'
  build-arm64:
    docker:
      - image: docker:18.09.9-git
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: docker build -t arm64 -f arm64.dockerfile .
          no_output_timeout: 3600 
      - run: docker run --name temp-container arm64 /bin/true
      - run: docker cp temp-container:/@sixriver/ .
      - run: docker rm temp-container
      - run: ls -la
      - persist_to_workspace:
          root: ./
          paths:
            - '@sixriver'
  upload:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - attach_workspace:
          at: .
      - run: ls -la
      - run: 
          name: Activate gcloud
          command: |
            echo "${CLIENT_SECRET}" | base64 -d > /tmp/client-secret.json
            gcloud auth activate-service-account --key-file /tmp/client-secret.json
      - run: 
          name: Upload to gcloud 
          command: |
            BINARY_PATH=$(dirname $(cat binary_path.txt))
            TARGET_PATH=$(dirname $(cat target_path.txt))
            ls -la ${BINARY_PATH}
            cp -r ${BINARY_PATH}/*.tar.gz .
            printf "gsutil cp -r *.tar.gz gs://public-nodejs-binary/@sixriver/${TARGET_PATH}/"
            gsutil cp -r *.tar.gz gs://public-nodejs-binary/@sixriver/${TARGET_PATH}/
            gsutil acl ch -r -u AllUsers:R gs://public-nodejs-binary/@sixriver/${TARGET_PATH}
  build:
    docker:
      - image: circleci/node:8.12.0
        environment:
          - MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
    steps:
      - checkout
      - run:
          name: Setup CI Environment
          command: |
            sudo apt-get update && sudo apt-get install -y build-essential libbluetooth-dev
            git submodule update --init
            ci_scripts/ci_tool.sh --setup_npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Npm Install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
              - ./node_modules
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: reports/junit/
          prefix: reports/junit/
      - store_test_results:
          path: reports/junit/
      - run:
          name: Run release
          command: ci_scripts/ci_tool.sh --run_release
      - run:
          name: Npm Publish
          command: npm publish
workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          context: 6rs-circle
      - build-arm64
      - build-amd64
      - upload:
          context: 6rs-circle
          requires:
            - build-amd64
            - build-arm64
